server:
  port: 8080

spring:
 datasource:
   url: jdbc:mysql://127.0.0.1:3306/resourcedb
   username: scheduleAppt
   password: scheduleAppt
   driverClassName: com.mysql.cj.jdbc.Driver

 jpa:
   hibernate:
     ddl-auto: update

 application:
   name: RESOURCE-SERVICE

 config:
   import: configserver:http://localhost:9296